function getEquipmentAt(x,y){return Object.values(currentEquipment()).find(e=>e.x===x&&e.y===y)}
function isOn(e){return state.kobito.x===e.x&&state.kobito.y===e.y}
function move(dx,dy){if(state.completed||state.failed)return;const size=currentStage().size;const nx=state.kobito.x+dx,ny=state.kobito.y+dy;if(nx<0||nx>=size||ny<0||ny>=size){reject("盤面の外には移動できません．");return}state.kobito={x:nx,y:ny};const dir=dx<0?"左":dx>0?"右":dy<0?"上":"下";tick(`小人が${dir}へ移動した．`)}
function takeMaterial(){if(state.completed||state.failed)return;const instruction=currentInstruction();if(!instruction||instruction.kind!=="take"){reject("今の命令は，材料を取る操作ではありません．");return}if(!isOn(currentEquipment().warehouse)){reject("倉庫と同じマスにいる必要があります．");return}if(state.holding){reject("小人は材料を1個までしか持てません．");return}state.holding=instruction.item;state.currentInstruction++;tick(`倉庫で「${instruction.item}」を取った．`)}
function putOnSlot(){if(state.completed||state.failed)return;const instruction=currentInstruction();if(!instruction||instruction.kind!=="put"){reject("今の命令は，材料置き場に置く操作ではありません．");return}const target=getEquipmentAt(state.kobito.x,state.kobito.y);if(!target||target.type!=="slot"){reject("材料置き場と同じマスにいる必要があります．");return}if(state.holding!==instruction.item){reject(`材料置き場に置く材料は「${instruction.item}」です．`);return}if(state.slots[target.slot]){reject(`材料置き場${target.slot}にはすでに材料があります．`);return}state.slots[target.slot]=state.holding;state.holding=null;state.currentInstruction++;tick(`材料置き場${target.slot}に「${instruction.item}」を置いた．`)}
function buildToy(){if(state.completed||state.failed)return;const stage=currentStage();const instruction=currentInstruction();if(!instruction||instruction.kind!=="build"){reject("今の命令は，組み立てる操作ではありません．");return}if(!isOn(currentEquipment().assembly)){reject("組立台と同じマスにいる必要があります．");return}if(state.holding){reject("小人が材料を持ったままでは組み立てられません．");return}const slotItems=Object.values(state.slots);const missing=stage.materials.filter(item=>!slotItems.includes(item));if(missing.length){reject(`組み立てには，材料置き場に「${stage.materials.join("」「")}」が1つずつ必要です．`);return}stage.slotNames.forEach(slot=>state.slots[slot]=null);state.holding=stage.product;state.currentInstruction++;tick(`材料置き場の材料を使って「${stage.product}」を作った．`)}
function putInFinishBox(){if(state.completed||state.failed)return;const instruction=currentInstruction();if(!instruction||instruction.kind!=="finish"){reject("今の命令は，完成箱に入れる操作ではありません．");return}if(!isOn(currentEquipment().finish)){reject("完成箱と同じマスにいる必要があります．");return}if(state.holding!==instruction.item){reject(`完成箱に入れるものは「${instruction.item}」です．`);return}state.holding=null;state.currentInstruction++;state.completed=state.currentInstruction>=currentInstructions().length;tick(state.completed?`完成箱に「${instruction.item}」を入れた．ステージクリア！`:`完成箱に「${instruction.item}」を入れた．次の命令へ進もう．`)}
function performAction(){const instruction=currentInstruction();if(!instruction){reject("実行する命令がありません．");return}if(instruction.kind==="take")takeMaterial();else if(instruction.kind==="put")putOnSlot();else if(instruction.kind==="build")buildToy();else if(instruction.kind==="finish")putInFinishBox()}
function checkFailure(){const stage=currentStage();if(!state.completed&&state.turn>stage.stars.one){state.failed=true;addLog("納期を過ぎてしまった．もう一度，移動距離を見直そう．")}}
function getStars(turn){const stars=currentStage().stars;if(turn<=stars.three)return"★★★";if(turn<=stars.two)return"★★";if(turn<=stars.one)return"★";return"星なし"}
