const itemIcon={"タイヤ":"🛞","ボディ":"🚗","くるま":"🚙","頭":"🤖","体":"🧱","足":"🦿","ロボット":"🦾"};
const stages=[
{id:1,name:"ステージ1",title:"ステージ1：材料置き場を使おう",lead:"材料置き場A/Bに材料をそろえて，組立台で「くるま」を完成させよう．",order:"くるま ×1",size:3,start:{x:1,y:1},slotNames:["A","B"],materials:["タイヤ","ボディ"],product:"くるま",stars:{three:16,two:20,one:24},equipment:{warehouse:{x:0,y:0,name:"倉庫",icon:"🏚️",type:"warehouse"},slotA:{x:1,y:0,name:"材料置き場A",icon:"🧺",type:"slot",slot:"A"},assembly:{x:2,y:0,name:"組立台",icon:"🔧",type:"assembly"},slotB:{x:2,y:1,name:"材料置き場B",icon:"🧺",type:"slot",slot:"B"},finish:{x:2,y:2,name:"完成箱",icon:"🎁",type:"finish"}},instructions:[{kind:"take",item:"タイヤ",text:"倉庫で「タイヤ」を取る"},{kind:"put",item:"タイヤ",text:"どちらかの材料置き場に「タイヤ」を置く"},{kind:"take",item:"ボディ",text:"倉庫で「ボディ」を取る"},{kind:"put",item:"ボディ",text:"空いている材料置き場に「ボディ」を置く"},{kind:"build",item:"くるま",text:"組立台で「くるま」を作る"},{kind:"finish",item:"くるま",text:"完成箱に「くるま」を入れる"}],hint:"タイヤとボディは材料置き場A/Bのどちらに置いてもよいので，2つの置き場に1つずつ材料を置き，その後に組立台へ移動して組み立ててください．"},
{id:2,name:"ステージ2",title:"ステージ2：3つの材料をそろえよう",lead:"3つの材料置き場を使って，組立台で「ロボット」を完成させよう．",order:"ロボット ×1",size:3,start:{x:1,y:1},slotNames:["A","B","C"],materials:["頭","体","足"],product:"ロボット",stars:{three:24,two:30,one:36},equipment:{warehouse:{x:0,y:0,name:"倉庫",icon:"🏚️",type:"warehouse"},slotA:{x:1,y:0,name:"材料置き場A",icon:"🧺",type:"slot",slot:"A"},assembly:{x:2,y:0,name:"組立台",icon:"🔧",type:"assembly"},slotB:{x:2,y:1,name:"材料置き場B",icon:"🧺",type:"slot",slot:"B"},slotC:{x:0,y:2,name:"材料置き場C",icon:"🧺",type:"slot",slot:"C"},finish:{x:2,y:2,name:"完成箱",icon:"🎁",type:"finish"}},instructions:[{kind:"take",item:"頭",text:"倉庫で「頭」を取る"},{kind:"put",item:"頭",text:"空いている材料置き場に「頭」を置く"},{kind:"take",item:"体",text:"倉庫で「体」を取る"},{kind:"put",item:"体",text:"空いている材料置き場に「体」を置く"},{kind:"take",item:"足",text:"倉庫で「足」を取る"},{kind:"put",item:"足",text:"空いている材料置き場に「足」を置く"},{kind:"build",item:"ロボット",text:"組立台で「ロボット」を作る"},{kind:"finish",item:"ロボット",text:"完成箱に「ロボット」を入れる"}],hint:"3つの材料は，材料置き場A/B/Cのどこに置いてもよいです．3つの置き場に材料を1つずつそろえてから，組立台でロボットを作ってください．"},
{id:3,name:"ステージ3",title:"ステージ3：同じ処理をくり返そう",lead:"同じ命令の流れをもう一度たどって，「くるま」を2台完成させよう．",order:"くるま ×2",size:3,start:{x:1,y:1},slotNames:["A","B"],materials:["タイヤ","ボディ"],product:"くるま",stars:{three:34,two:42,one:50},equipment:{warehouse:{x:0,y:0,name:"倉庫",icon:"🏚️",type:"warehouse"},slotA:{x:1,y:0,name:"材料置き場A",icon:"🧺",type:"slot",slot:"A"},assembly:{x:2,y:0,name:"組立台",icon:"🔧",type:"assembly"},slotB:{x:2,y:1,name:"材料置き場B",icon:"🧺",type:"slot",slot:"B"},finish:{x:2,y:2,name:"完成箱",icon:"🎁",type:"finish"}},instructions:[{kind:"take",item:"タイヤ",text:"1台目：倉庫で「タイヤ」を取る"},{kind:"put",item:"タイヤ",text:"1台目：どちらかの材料置き場に「タイヤ」を置く"},{kind:"take",item:"ボディ",text:"1台目：倉庫で「ボディ」を取る"},{kind:"put",item:"ボディ",text:"1台目：空いている材料置き場に「ボディ」を置く"},{kind:"build",item:"くるま",text:"1台目：組立台で「くるま」を作る"},{kind:"finish",item:"くるま",text:"1台目：完成箱に「くるま」を入れる"},{kind:"take",item:"タイヤ",text:"2台目：倉庫で「タイヤ」を取る"},{kind:"put",item:"タイヤ",text:"2台目：どちらかの材料置き場に「タイヤ」を置く"},{kind:"take",item:"ボディ",text:"2台目：倉庫で「ボディ」を取る"},{kind:"put",item:"ボディ",text:"2台目：空いている材料置き場に「ボディ」を置く"},{kind:"build",item:"くるま",text:"2台目：組立台で「くるま」を作る"},{kind:"finish",item:"くるま",text:"2台目：完成箱に「くるま」を入れる"}],hint:"1台目を完成箱に入れたあと，同じ流れをもう一度くり返します．命令列のどこまで終わったかを見ながら，2台目も完成させてください．"}
];
let currentStageIndex=0;
function currentStage(){return stages[currentStageIndex]}
function currentEquipment(){return currentStage().equipment}
function currentInstructions(){return currentStage().instructions}
function currentInstruction(){return currentInstructions()[state.currentInstruction]}
